version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_management
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_HOST: '%'  # ← AJOUTE CETTE LIGNE
    command: 
      - --bind-address=0.0.0.0  # ← ET CETTE LIGNE
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  student-app:
    build: .
    container_name: student-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/student_management
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8083:8089"
    depends_on:
      - mysql-db

volumes:
  mysql_data: